modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/LegacyHypixel/NoTwitchKeybind"
license = "MPL-2.0"

[[mods]]
modId = "notwitchkeybind"
version = "${version}"
displayName = "No Twitch Keybind"
authors = "Crosby"
description = '''
    Removes the F6 Twitch stream keybind.
'''

[[dependencies.notwitchkeybind]]
modId="minecraft"
mandatory=true
versionRange="[1.8.9]"
ordering="NONE"
side="BOTH"